### PR TITLE
adding time tracking tool

### PR DESCRIPTION
**Pull request by angihe93**
Hi, I added a time tracking tool for logged in users. The user can hover over the button on the bottom right of the page to see how long they've been engaged with a specific controller. It gets the time by querying the database for total milliseconds engaged with the current controller. I've only tested it on my desktop browsers and not on mobile. [Here's](https://drive.google.com/file/d/1L0bPX1f-cfEN5JxK4KHp99EoJkFtnLbk/view?usp=sharing) what it looks like in action.

### CODE REVIEW

**Comment by kennethgoodman** [comment]
Great job! Did you test this E2E? Does it work?

**Comment by angihe93** [comment]
Where are the comments? Not seeing them for some reason

**Comment by angihe93** [comment]
Forgot to not count idle time (> 25000ms based on the engagement description in the group project assignment on Canvas?), will fix that right now

**Comment by angihe93** [comment]
should >25000ms engagements be counted as 25000ms or not be counted at all?

**Comment by kennethgoodman** [comment]
> Where are the comments? Not seeing them for some reason
On the code, see "Files Changed"

> should >25000ms engagements be counted as 25000ms or not be counted at all?
Not counted at all, but maybe fairer is counting 3 seconds

**Comment by angihe93** [comment]
i've removed the comments and made >25000ms engagements count as 0ms (probably better to show the undercount for students)

**Review by kennethgoodman — APPROVED** [review]

**Pull request merged**
