### PR TITLE
Echo RecSys

### PR DESCRIPTION
**Pull request by pochl**
- All extra files and folders created by Echo team are placed in `services/backend/src/echo_space` folder.
- Our controller is put within  `services/backend/src/recommendation_system/recommendation_flow/controllers/ExampleController.py` in the class `ExampleController`.
- There are multiple files and notebooks under `echo_space` that will not be called during live testing. They were used to create features and output beforehand to be used for the live testing.

### CODE REVIEW

**Review by kennethgoodman — COMMENTED** [review]
Will approve once you add back the deleted files

**Comment by pochl** [comment]
Done! Sorry for the delay!

**Comment by kennethgoodman** [comment]
now 231 files changed? something weird happened

**Comment by pochl** [comment]
hmmm wait let me check

**Comment by pochl** [comment]
Fixed!

**Review by kennethgoodman — COMMENTED** [review]
almost there

Let's not update ExampleGenerator, Examplecontroller

Or the sql files (I believe I by mistake accepted Delta updating 01_user) so that one is ok to change

**Comment by pochl** [comment]
so I've revert the change on examplecontroller and generator. I'm not quite sure what you meant by the sql files?

**Review by kennethgoodman — APPROVED** [review]

**Pull request merged**
