### PR TITLE
New Golf Assignment1

### PR DESCRIPTION
**Pull request by zwht81**

### CODE REVIEW

**Comment by zwht81** [comment]
Hi, professor. We have some pkl file that I couldn't add to it. How can I solve the problem?

**Comment by kennethgoodman** [comment]
what type of ppl file?

**Comment by zwht81** [comment]
.pkl, we use it in our two_tower_model

**Comment by zwht81** [comment]
Can I sent it to you seperately? And add such pkl in the \src\recommendation_system\ml_models\golf, the two tower model can run successfully.

**Comment by kennethgoodman** [comment]
ideally not, but if we can't get it to work, I'll try to figure it out, what is the error?

**Comment by zwht81** [comment]
ok, let me try to upload it.

**Review by kennethgoodman — APPROVED** [review]

**Pull request merged**
