### PR TITLE
Group Foxtrot

### PR DESCRIPTION
**Pull request by hywvivi98**
This is the updated rec model from Foxtrot, file changes are the following:
- Candidate Generator: `services/backend/src/recommendation_system/recommendation_flow/candidate_generators/FoxtrotGenerator.py`
- Filter: `services/backend/src/recommendation_system/recommendation_flow/filtering/FoxtrotFilter.py`
- Predictor: `services/backend/src/recommendation_system/recommendation_flow/model_prediction/FoxtrotModel.py`
- Ranker:
`services/backend/src/recommendation_system/recommendation_flow/ranking/FoxtrotRanker.py`

Other Specifications:
- files under `services/backend/src/recommendation_system/ml_models` are for importing controller
- the `clustering.py` file under `services/backend/src/recommendation_system/recommendation_flow/candidate_generators` are some auxiliary code to generate the csv with users clusters (with the sample users cluster named `users_clusters2.csv`)
- the file `services/backend/src/recommendation_system/recommendation_flow/candidate_generators/Preprocessing.py` is for preprocessing

### CODE REVIEW

**Review by kennethgoodman — COMMENTED** [review]
1. please have all files have "Foxtrot" before the filename or have it in a folder named "foxtrot" You can see examples from other teams in the codebasa.
2. please delete commented code
3. you're reading the CSV file every time, maybe read it just once by putting it at the top of the file outside the function?

once done, I will merge

**Review by kennethgoodman — APPROVED** [review]

**Review by kennethgoodman — CHANGES_REQUESTED** [review]
Please update users_clusters2, content_features, and user_features files to have Foxtrot before them, or in a folder called Foxtrot

**Comment by kennethgoodman** [comment]
2 more files please, lgb_model (I think delete this as you have one prefixed and one not) , user_clusters2

**Comment by hywvivi98** [comment]
> 2 more files please, lgb_model (I think delete this as you have one prefixed and one not) , user_clusters2

hi professor, we just opened up a new PR trying to fix the blank content error, hope it will work:(

**Pull request merged**
